import {CalendarIcon} from "@sanity/icons"
import {defineField, defineType} from "sanity"

const eventCategories = [
  {title: "Jóvenes", value: "jovenes"},
  {title: "Evangelismo", value: "evangelismo"},
  {title: "Servicio", value: "servicio"},
  {title: "Niños", value: "ninos"},
  {title: "Matrimonios", value: "matrimonios"},
  {title: "Estudios", value: "estudios"},
  {title: "Congreso", value: "congreso"},
  {title: "Damas", value: "damas"},
  {title: "Caballeros", value: "caballeros"},
]

const ministries = [
  {title: "Ministerio de Niños", value: "Ministerio de Ninos"},
  {title: "Generación Que Arde", value: "Generacion Que Arde"},
  {title: "Semillas Que Arden", value: "Generacion Que Arden"},
  {title: "Las que no retroceden", value: "Las que no retroceden" },
  {title: "Hombres de Valor", value: "Hombres de Valor" },
  {title: "Matrimonios", value: "Matrimonios"},
  {title: "Adoración", value: "Adoracion"},
  {title: "Kit Dorado", value: "Kit Dorado" },
  {title: "Misiones", value: "Misiones" },
]

const timeOptions = [
  {title: "12:00 AM", value: "00:00"},
  {title: "12:30 AM", value: "00:30"},
  {title: "1:00 AM", value: "01:00"},
  {title: "1:30 AM", value: "01:30"},
  {title: "2:00 AM", value: "02:00"},
  {title: "2:30 AM", value: "02:30"},
  {title: "3:00 AM", value: "03:00"},
  {title: "3:30 AM", value: "03:30"},
  {title: "4:00 AM", value: "04:00"},
  {title: "4:30 AM", value: "04:30"},
  {title: "5:00 AM", value: "05:00"},
  {title: "5:30 AM", value: "05:30"},
  {title: "6:00 AM", value: "06:00"},
  {title: "6:30 AM", value: "06:30"},
  {title: "7:00 AM", value: "07:00"},
  {title: "7:30 AM", value: "07:30"},
  {title: "8:00 AM", value: "08:00"},
  {title: "8:30 AM", value: "08:30"},
  {title: "9:00 AM", value: "09:00"},
  {title: "9:30 AM", value: "09:30"},
  {title: "10:00 AM", value: "10:00"},
  {title: "10:30 AM", value: "10:30"},
  {title: "11:00 AM", value: "11:00"},
  {title: "11:30 AM", value: "11:30"},
  {title: "12:00 PM", value: "12:00"},
  {title: "12:30 PM", value: "12:30"},
  {title: "1:00 PM", value: "13:00"},
  {title: "1:30 PM", value: "13:30"},
  {title: "2:00 PM", value: "14:00"},
  {title: "2:30 PM", value: "14:30"},
  {title: "3:00 PM", value: "15:00"},
  {title: "3:30 PM", value: "15:30"},
  {title: "4:00 PM", value: "16:00"},
  {title: "4:30 PM", value: "16:30"},
  {title: "5:00 PM", value: "17:00"},
  {title: "5:30 PM", value: "17:30"},
  {title: "6:00 PM", value: "18:00"},
  {title: "6:30 PM", value: "18:30"},
  {title: "7:00 PM", value: "19:00"},
  {title: "7:30 PM", value: "19:30"},
  {title: "8:00 PM", value: "20:00"},
  {title: "8:30 PM", value: "20:30"},
  {title: "9:00 PM", value: "21:00"},
  {title: "9:30 PM", value: "21:30"},
  {title: "10:00 PM", value: "22:00"},
  {title: "10:30 PM", value: "22:30"},
  {title: "11:00 PM", value: "23:00"},
  {title: "11:30 PM", value: "23:30"},
]

export const event = defineType({
  name: "event",
  title: "Eventos",
  type: "document",
  icon: CalendarIcon,
  fields: [
    defineField({
      name: "title",
      title: "Titulo",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Identificador",
      type: "slug",
      options: {source: "title"},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "date",
      title: "Fecha",
      type: "date",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "startTime",
      title: "Hora de comienzo",
      type: "string",
      options: {
        list: timeOptions,
      },
    }),
    defineField({
      name: "endTime",
      title: "Hora de cierre",
      type: "string",
      options: {
        list: timeOptions,
      },
    }),
    defineField({
      name: "location",
      title: "Lugar",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "description",
      title: "Descripcion",
      type: "text",
      rows: 4,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "category",
      title: "Categoria",
      type: "string",
      options: {
        list: eventCategories,
        layout: "radio",
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "ministry",
      title: "Ministerio",
      type: "string",
      options: {
        list: ministries,
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroImage",
      title: "Imagen principal",
      type: "image",
      options: {hotspot: true},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "cardImage",
      title: "Imagen para tarjeta",
      type: "image",
      options: {hotspot: true},
      description: "Opcional. Si se deja vacia se usa la imagen principal.",
    }),
    defineField({
      name: "featured",
      title: "Evento destacado",
      type: "boolean",
      initialValue: false,
    }),
    defineField({
      name: "isActive",
      title: "Publicado en la pagina",
      type: "boolean",
      initialValue: true,
    }),
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "date",
      media: "heroImage",
    },
  },
})
